name: End-to-end tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          headless: true
          project: ./src/__e2e-test__
          build: yarn build
          start: yarn start
          wait-on: http://localhost:3000
        env:
          NODE_ENV: development
          CMS_ENDPOINT: ${{ secrets.CMS_ENDPOINT }}
          CMS_APIKEY: ${{ secrets.CMS_APIKEY }}
