name: End-to-end tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test:e2e
        env:
          NODE_ENV: development
          CMS_ENDPOINT: ${{ secrets.CMS_ENDPOINT }}
          CMS_APIKEY: ${{ secrets.CMS_APIKEY }}
